
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/wvw/.nvm/versions/node/v23.2.0/bin/"
      - "/Users/wvw/google-cloud-sdk/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.13/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Users/wvw/bin/"
      - "/Applications/MAMP/bin/php/php8.2.0/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/X11/bin/"
      - "/Library/TeX/texbin/"
      - "/Applications/Postgres.app/Contents/Versions/latest/bin/"
      - "/Users/wvw/.cargo/bin/"
      - "/Users/wvw/.cabal/bin/"
      - "/Users/wvw/.ghcup/bin/"
      - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/"
      - "/opt/eye/bin/"
      - "/opt/apache-maven-3.9.2/bin/"
      - "/Applications/MAMP/bin/php/php8.2.0/bin/php/"
      - "/opt/nemo-0.6.0/"
      - "/Users/wvw/.cpm/bin/"
    searched_directories:
      - "/Users/wvw/.nvm/versions/node/v23.2.0/bin/uname"
      - "/Users/wvw/google-cloud-sdk/bin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.13/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/opt/local/bin/uname"
      - "/opt/local/sbin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/wvw/.nvm/versions/node/v23.2.0/bin"
        - "/Users/wvw/google-cloud-sdk/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
        - "/Users/wvw/google-cloud-sdk/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "~/bin"
        - "/Applications/MAMP/bin/php/php8.2.0/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/X11/bin"
        - "/Library/TeX/texbin"
        - "/Applications/Postgres.app/Contents/Versions/latest/bin"
        - "/Users/wvw/.cargo/bin"
        - "/Users/wvw/.cabal/bin"
        - "/Users/wvw/.ghcup/bin"
        - "~/bin"
        - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
        - "/opt/eye/bin"
        - "/opt/apache-maven-3.9.2/bin"
        - "/Applications/MAMP/bin/php/php8.2.0/bin/php"
        - "/opt/nemo-0.6.0"
        - "~/.ghcup/bin"
        - "~/.cpm/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/wvw/.nvm/versions/node/v23.2.0/bin/"
      - "/Users/wvw/google-cloud-sdk/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.13/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/opt/local/bin/"
      - "/opt/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Users/wvw/bin/"
      - "/Applications/MAMP/bin/php/php8.2.0/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/X11/bin/"
      - "/Library/TeX/texbin/"
      - "/Applications/Postgres.app/Contents/Versions/latest/bin/"
      - "/Users/wvw/.cargo/bin/"
      - "/Users/wvw/.cabal/bin/"
      - "/Users/wvw/.ghcup/bin/"
      - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/"
      - "/opt/eye/bin/"
      - "/opt/apache-maven-3.9.2/bin/"
      - "/Applications/MAMP/bin/php/php8.2.0/bin/php/"
      - "/opt/nemo-0.6.0/"
      - "/Users/wvw/.cpm/bin/"
    searched_directories:
      - "/Users/wvw/.nvm/versions/node/v23.2.0/bin/install_name_tool"
      - "/Users/wvw/google-cloud-sdk/bin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.13/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/opt/local/bin/install_name_tool"
      - "/opt/local/sbin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/wvw/.nvm/versions/node/v23.2.0/bin"
        - "/Users/wvw/google-cloud-sdk/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
        - "/Users/wvw/google-cloud-sdk/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/opt/local/bin"
        - "/opt/local/sbin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "~/bin"
        - "/Applications/MAMP/bin/php/php8.2.0/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/X11/bin"
        - "/Library/TeX/texbin"
        - "/Applications/Postgres.app/Contents/Versions/latest/bin"
        - "/Users/wvw/.cargo/bin"
        - "/Users/wvw/.cabal/bin"
        - "/Users/wvw/.ghcup/bin"
        - "~/bin"
        - "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
        - "/opt/eye/bin"
        - "/opt/apache-maven-3.9.2/bin"
        - "/Applications/MAMP/bin/php/php8.2.0/bin/php"
        - "/opt/nemo-0.6.0"
        - "~/.ghcup/bin"
        - "~/.cpm/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.13/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
